In [56]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [57]:
df_Mobile = pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_Android.xlsx')  
df_Mobile

Name    Red  Green  Blue  Gray  Contrast  Energy  Homogeneity   Asm  \
0    BAL21.png   4.90   4.04  3.97  4.29     29.05    0.85         0.87  0.73   
1    BAL22.png   5.32   4.56  4.41  4.76     31.18    0.85         0.87  0.73   
2    BAL23.png   5.65   4.84  4.69  5.06     38.00    0.84         0.86  0.71   
3    BAL24.png   6.06   5.20  5.04  5.44     42.86    0.84         0.86  0.70   
4    BAL25.png   6.05   5.20  5.05  5.43     41.67    0.84         0.86  0.71   
..         ...    ...    ...   ...   ...       ...     ...          ...   ...   
115   CD26.png   9.66   8.99  9.35  9.24     65.77    0.76         0.79  0.58   
116   CD27.png   9.60   8.83  9.11  9.09     60.54    0.73         0.76  0.53   
117   CD28.png   9.59   8.94  9.26  9.17     63.89    0.73         0.76  0.53   
118   CD29.png  10.01   9.35  9.66  9.58     74.65    0.72         0.76  0.52   
119   CD30.png   8.60   8.02  8.29  8.22     56.27    0.75         0.79  0.57   

     Correlation  Dissimilarity  Group    pH  
0           0.90           1.40      1  4.86  
1           0.91           1.43      1  4.86  
2           0.90           1.66      1  4.86  
3           0.89           1.77      1  4.86  
4           0.90           1.68      1  4.86  
..           ...            ...    ...   ...  
115         0.91           2.64      4  5.43  
116         0.90           2.70      4  5.43  
117         0.90           2.75      4  5.43  
118         0.89           3.00      4  5.43  
119         0.90           2.45      4  5.43  

[120 rows x 13 columns]

In [58]:
# Iphone feature (Mobile)
BAL_1 = df_Mobile.iloc[0:10,1:4] #BAL
BPL_1 = df_Mobile.iloc[10:20,1:4] #BPL
CM_2= df_Mobile.iloc[20:30,1:4] #CM
BAM_3 = df_Mobile.iloc[50:60,1:4]#BAM
BPM_3 = df_Mobile.iloc[60:70,1:4]#BPM
BAD_4 = df_Mobile.iloc[90:100,1:4]#BAD
PD_4 = df_Mobile.iloc[100:110,1:4]#PD
PM_2= df_Mobile.iloc[30:40,1:4]#PM


In [59]:
G1= pd.concat([BAL_1, BPL_1])
feature_G1 = G1.values
G2= pd.concat([CM_2,PM_2])
feature_G2 = G2.values
G3=pd.concat([BAM_3,BPM_3])
feature_G3 = G3.values
G4=pd.concat([BAD_4,PD_4])
feature_G4 = G4.values

In [60]:
df=df_Mobile
Target_BAL_1 = df.iloc[0:10,11:12]#BAL
Target_BPL_1 = df.iloc[10:20,11:12]#BPL
Target_CM_2= df.iloc[20:30,11:12]#CM
Target_BAM_3 = df.iloc[50:60,11:12]#BAM
Target_BPM_3 = df.iloc[60:70,11:12]#BPM
Target_BAD_4 = df.iloc[90:100,11:12]#BAD
Target_PD_4 = df.iloc[100:110,11:12]#PD
Target_PM_2= df.iloc[30:40,11:12]#PM


In [61]:
G1_target = pd.concat([Target_BAL_1, Target_BPL_1]).values
G2_target = pd.concat([Target_CM_2,Target_PM_2]).values
G3_target = pd.concat([Target_BAM_3,Target_BPM_3]).values
G4_target = pd.concat([Target_BAD_4,Target_PD_4]).values

In [62]:
# # 80% training and 20% test
# fea_train_G1, fea_test_G1, tar_train_G1, tar_test_G1 = train_test_split(feature_G1,G1_target, test_size=0.2, random_state=1)
# fea_train_G2, fea_test_G2, tar_train_G2, tar_test_G2 = train_test_split(feature_G2,G2_target, test_size=0.2, random_state=1)
# fea_train_G3, fea_test_G3, tar_train_G3, tar_test_G3 = train_test_split(feature_G3,G3_target, test_size=0.2, random_state=1)
# fea_train_G4, fea_test_G4, tar_train_G4, tar_test_G4 = train_test_split(feature_G4,G4_target, test_size=0.2, random_state=1)

In [63]:
main_feature_train = np.concatenate((feature_G1, feature_G2,feature_G3,feature_G4), axis=0)
main_target_train=np.concatenate((G1_target, G2_target,G3_target,G4_target), axis=0)
# main_feature_test = np.concatenate(( fea_test_G1,  fea_test_G2, fea_test_G3, fea_test_G4), axis=0)
# main_target_test=np.concatenate((tar_test_G1, tar_test_G2,tar_test_G3,tar_test_G4), axis=0)

In [64]:
dTree = DecisionTreeClassifier(max_depth =30, min_samples_leaf = 4, max_features = 3)
dTree.fit(main_feature_train,main_target_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=30, max_features=3, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [65]:
  
df_all =pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_Mobile_v2.xlsx')   
df = df_all

In [66]:
# Andriod feature (Mobile)
df_Mobile = df_all
BAL_1 = df_Mobile.iloc[0:10,1:4] #BAL
BPL_1 = df_Mobile.iloc[10:20,1:4] #BPL
CM_2= df_Mobile.iloc[20:30,1:4] #CM
BAM_3 = df_Mobile.iloc[50:60,1:4]#BAM
BPM_3 = df_Mobile.iloc[60:70,1:4]#BPM
BAD_4 = df_Mobile.iloc[90:100,1:4]#BAD
PD_4 = df_Mobile.iloc[100:110,1:4]#PD
PM_2= df_Mobile.iloc[30:40,1:4]#PM


In [67]:
G1= pd.concat([BAL_1, BPL_1])
feature_G1 = G1.values
G2= pd.concat([CM_2,PM_2])
feature_G2 = G2.values
G3=pd.concat([BAM_3,BPM_3])
feature_G3 = G3.values
G4=pd.concat([BAD_4,PD_4])
feature_G4 = G4.values
len(feature_G4)

20

In [68]:

Target_BAL_1 = df_Mobile.iloc[0:10,11:12] #BAL
Target_BPL_1 = df_Mobile.iloc[10:20,11:12] #BPL
Target_CM_2= df_Mobile.iloc[20:30,11:12] #CM
Target_BAM_3 = df_Mobile.iloc[50:60,11:12]#BAM
Target_BPM_3 = df_Mobile.iloc[60:70,11:12]#BPM
Target_BAD_4 = df_Mobile.iloc[90:100,11:12]#BAD
Target_PD_4 = df_Mobile.iloc[100:110,11:12]#PD
Target_PM_2= df_Mobile.iloc[30:40,11:12]#PM

In [69]:
G1_target = pd.concat([Target_BAL_1, Target_BPL_1]).values
G2_target = pd.concat([Target_CM_2,Target_PM_2]).values
G3_target = pd.concat([Target_BAM_3,Target_BPM_3]).values
G4_target = pd.concat([Target_BAD_4,Target_PD_4]).values
G4_target

array([[4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4]], dtype=int64)

In [70]:

# main_feature_train = np.concatenate((fea_train_G1, fea_train_G2,fea_train_G3,fea_train_G4), axis=0)
# main_target_train=np.concatenate((tar_train_G1, tar_train_G2,tar_train_G3,tar_train_G4), axis=0)
main_feature_test = np.concatenate(( feature_G1,feature_G2,feature_G3,feature_G4), axis=0)
main_target_test=np.concatenate((G1_target,G2_target,G3_target,G4_target), axis=0)
main_target_test


array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4]], dtype=int64)

In [71]:
MOBILE_TRAIN_DSLR_TEST = dTree.predict(main_feature_test)
MOBILE_TRAIN_DSLR_TEST

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [72]:

print("\nDesicion Tree")

print("\nEvaluation of DTree Model : \n", classification_report(main_target_test, MOBILE_TRAIN_DSLR_TEST))


Desicion Tree

Evaluation of DTree Model : 
               precision    recall  f1-score   support

           1       0.26      1.00      0.41        20
           2       0.00      0.00      0.00        20
           3       0.00      0.00      0.00        20
           4       0.00      0.00      0.00        20

    accuracy                           0.25        80
   macro avg       0.06      0.25      0.10        80
weighted avg       0.06      0.25      0.10        80



c:\users\u5988116\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
