In [114]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [115]:
df_Mobile = pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_Mobile_v2.xlsx')  
df_Mobile

Name    Red  Green   Blue   Gray  Contrast  Energy  Homogeneity  \
0    BAL11.png  14.22  10.22   6.14  10.95     98.80    0.69         0.71   
1    BAL12.png  12.11   8.68   5.24   9.31     91.88    0.72         0.74   
2    BAL13.png   9.49   6.79   4.06   7.28     60.24    0.76         0.78   
3    BAL14.png  10.70   7.60   4.55   8.18     75.34    0.74         0.76   
4    BAL15.png   9.77   6.98   4.23   7.50     67.35    0.75         0.77   
..         ...    ...    ...    ...    ...       ...     ...          ...   
115   CD16.png  19.60  16.13  14.09  16.93    187.53    0.66         0.68   
116   CD17.png  10.34   8.11   6.52   8.59     95.70    0.69         0.72   
117   CD18.png  11.42   8.95   7.02   9.47     93.11    0.67         0.69   
118   CD19.png  10.79   8.41   6.69   8.93     87.49    0.66         0.70   
119   CD20.png   9.36   7.37   5.84   7.79     76.09    0.69         0.71   

      Asm  Correlation  Dissimilarity  Group    pH  
0    0.48         0.86           4.32      1  4.86  
1    0.52         0.85           3.92      1  4.86  
2    0.58         0.86           3.02      1  4.86  
3    0.54         0.85           3.44      1  4.86  
4    0.57         0.85           3.09      1  4.86  
..    ...          ...            ...    ...   ...  
115  0.43         0.88           5.94      4  5.43  
116  0.48         0.81           4.10      4  5.43  
117  0.44         0.83           4.32      4  5.43  
118  0.44         0.82           4.10      4  5.43  
119  0.47         0.81           3.77      4  5.43  

[120 rows x 13 columns]

In [116]:
# Train Mobile iphone
df= df_Mobile
d1= df.iloc[:, 0:3]
d2= df.iloc[:,4:5]
d3= df.iloc[:,6:10]
d4 = df.iloc[:,11:12]
hi_df = pd.concat([d1,d2,d3,d4], axis=1)
hi_df

Name    Red  Green   Gray  Energy  Homogeneity   Asm  Correlation  \
0    BAL11.png  14.22  10.22  10.95    0.69         0.71  0.48         0.86   
1    BAL12.png  12.11   8.68   9.31    0.72         0.74  0.52         0.85   
2    BAL13.png   9.49   6.79   7.28    0.76         0.78  0.58         0.86   
3    BAL14.png  10.70   7.60   8.18    0.74         0.76  0.54         0.85   
4    BAL15.png   9.77   6.98   7.50    0.75         0.77  0.57         0.85   
..         ...    ...    ...    ...     ...          ...   ...          ...   
115   CD16.png  19.60  16.13  16.93    0.66         0.68  0.43         0.88   
116   CD17.png  10.34   8.11   8.59    0.69         0.72  0.48         0.81   
117   CD18.png  11.42   8.95   9.47    0.67         0.69  0.44         0.83   
118   CD19.png  10.79   8.41   8.93    0.66         0.70  0.44         0.82   
119   CD20.png   9.36   7.37   7.79    0.69         0.71  0.47         0.81   

     Group  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
115      4  
116      4  
117      4  
118      4  
119      4  

[120 rows x 9 columns]

In [117]:
# Iphone feature (Mobile)
df_Mobile = hi_df
BAL_1 = df_Mobile.iloc[0:10,1:8] #BAL
BPL_1 = df_Mobile.iloc[10:20,1:8] #BPL
CM_2= df_Mobile.iloc[20:30,1:8] #CM
BAM_3 = df_Mobile.iloc[50:60,1:8]#BAM
BPM_3 = df_Mobile.iloc[60:70,1:8]#BPM
BAD_4 = df_Mobile.iloc[90:100,1:8]#BAD
PD_4 = df_Mobile.iloc[100:110,1:8]#PD
PM_2= df_Mobile.iloc[30:40,1:8]#PM
PD_4

Red  Green  Gray  Energy  Homogeneity   Asm  Correlation
100   6.88   5.39  5.71    0.74         0.77  0.55         0.80
101  10.42   7.99  8.51    0.69         0.71  0.47         0.82
102   8.95   6.76  7.24    0.69         0.72  0.48         0.82
103  10.56   8.16  8.68    0.68         0.70  0.46         0.81
104  11.32   8.80  9.34    0.66         0.69  0.43         0.82
105   5.69   5.00  5.18    0.76         0.78  0.57         0.81
106   6.25   5.46  5.64    0.73         0.76  0.53         0.80
107   9.02   7.70  7.99    0.66         0.69  0.44         0.77
108   7.14   6.31  6.50    0.72         0.74  0.52         0.79
109   6.60   5.75  5.94    0.72         0.75  0.52         0.79

In [118]:
G1= pd.concat([BAL_1, BPL_1])
feature_G1 = G1.values
G2= pd.concat([CM_2,PM_2])
feature_G2 = G2.values
G3=pd.concat([BAM_3,BPM_3])
feature_G3 = G3.values
G4=pd.concat([BAD_4,PD_4])
feature_G4 = G4.values

In [119]:
df=df_Mobile
Target_BAL_1 = df.iloc[0:10,8:9]#BAL
Target_BPL_1 = df.iloc[10:20,8:9]#BPL
Target_CM_2= df.iloc[20:30,8:9]#CM
Target_BAM_3 = df.iloc[50:60,8:9]#BAM
Target_BPM_3 = df.iloc[60:70,8:9]#BPM
Target_BAD_4 = df.iloc[90:100,8:9]#BAD
Target_PD_4 = df.iloc[100:110,8:9]#PD
Target_PM_2= df.iloc[30:40,8:9]#PM


In [120]:
G1_target = pd.concat([Target_BAL_1, Target_BPL_1]).values
G2_target = pd.concat([Target_CM_2,Target_PM_2]).values
G3_target = pd.concat([Target_BAM_3,Target_BPM_3]).values
G4_target = pd.concat([Target_BAD_4,Target_PD_4]).values

In [121]:
# # 80% training and 20% test
# fea_train_G1, fea_test_G1, tar_train_G1, tar_test_G1 = train_test_split(feature_G1,G1_target, test_size=0.2, random_state=1)
# fea_train_G2, fea_test_G2, tar_train_G2, tar_test_G2 = train_test_split(feature_G2,G2_target, test_size=0.2, random_state=1)
# fea_train_G3, fea_test_G3, tar_train_G3, tar_test_G3 = train_test_split(feature_G3,G3_target, test_size=0.2, random_state=1)
# fea_train_G4, fea_test_G4, tar_train_G4, tar_test_G4 = train_test_split(feature_G4,G4_target, test_size=0.2, random_state=1)

In [122]:
main_feature_train = np.concatenate((feature_G1, feature_G2,feature_G3,feature_G4), axis=0)
main_target_train=np.concatenate((G1_target, G2_target,G3_target,G4_target), axis=0)
# main_feature_test = np.concatenate(( fea_test_G1,  fea_test_G2, fea_test_G3, fea_test_G4), axis=0)
# main_target_test=np.concatenate((tar_test_G1, tar_test_G2,tar_test_G3,tar_test_G4), axis=0)

In [133]:
dTree = DecisionTreeClassifier(max_depth =15, min_samples_leaf = 4, max_features = 7)
dTree.fit(main_feature_train,main_target_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=15, max_features=7, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [134]:
  
df_all =pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_Android.xlsx')   
df = df_all

In [135]:
# Train Mobile

d1= df.iloc[:, 0:3]
d2= df.iloc[:,4:5]
d3= df.iloc[:,6:10]
d4 = df.iloc[:,11:12]
hi_df = pd.concat([d1,d2,d3,d4], axis=1)
hi_df

Name    Red  Green  Gray  Energy  Homogeneity   Asm  Correlation  \
0    BAL21.png   4.90   4.04  4.29    0.85         0.87  0.73         0.90   
1    BAL22.png   5.32   4.56  4.76    0.85         0.87  0.73         0.91   
2    BAL23.png   5.65   4.84  5.06    0.84         0.86  0.71         0.90   
3    BAL24.png   6.06   5.20  5.44    0.84         0.86  0.70         0.89   
4    BAL25.png   6.05   5.20  5.43    0.84         0.86  0.71         0.90   
..         ...    ...    ...   ...     ...          ...   ...          ...   
115   CD26.png   9.66   8.99  9.24    0.76         0.79  0.58         0.91   
116   CD27.png   9.60   8.83  9.09    0.73         0.76  0.53         0.90   
117   CD28.png   9.59   8.94  9.17    0.73         0.76  0.53         0.90   
118   CD29.png  10.01   9.35  9.58    0.72         0.76  0.52         0.89   
119   CD30.png   8.60   8.02  8.22    0.75         0.79  0.57         0.90   

     Group  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
115      4  
116      4  
117      4  
118      4  
119      4  

[120 rows x 9 columns]

In [136]:
# Andriod feature (Mobile)
df_Mobile = hi_df
BAL_1 = df_Mobile.iloc[0:10,1:8] #BAL
BPL_1 = df_Mobile.iloc[10:20,1:8] #BPL
CM_2= df_Mobile.iloc[20:30,1:8] #CM
BAM_3 = df_Mobile.iloc[50:60,1:8]#BAM
BPM_3 = df_Mobile.iloc[60:70,1:8]#BPM
BAD_4 = df_Mobile.iloc[90:100,1:8]#BAD
PD_4 = df_Mobile.iloc[100:110,1:8]#PD
PM_2= df_Mobile.iloc[30:40,1:8]#PM
BAL_1

Red  Green  Gray  Energy  Homogeneity   Asm  Correlation
0  4.90   4.04  4.29    0.85         0.87  0.73         0.90
1  5.32   4.56  4.76    0.85         0.87  0.73         0.91
2  5.65   4.84  5.06    0.84         0.86  0.71         0.90
3  6.06   5.20  5.44    0.84         0.86  0.70         0.89
4  6.05   5.20  5.43    0.84         0.86  0.71         0.90
5  6.30   5.37  5.64    0.84         0.86  0.71         0.89
6  8.35   7.31  7.59    0.80         0.82  0.64         0.90
7  7.02   5.97  6.26    0.82         0.84  0.68         0.89
8  7.70   6.60  6.91    0.81         0.83  0.66         0.89
9  7.64   6.54  6.86    0.81         0.83  0.65         0.89

In [137]:
G1= pd.concat([BAL_1, BPL_1])
feature_G1 = G1.values
G2= pd.concat([CM_2,PM_2])
feature_G2 = G2.values
G3=pd.concat([BAM_3,BPM_3])
feature_G3 = G3.values
G4=pd.concat([BAD_4,PD_4])
feature_G4 = G4.values
len(feature_G4)

20

In [138]:

Target_BAL_1 = df_Mobile.iloc[0:10,8:9] #BAL
Target_BPL_1 = df_Mobile.iloc[10:20,8:9] #BPL
Target_CM_2= df_Mobile.iloc[20:30,8:9] #CM
Target_BAM_3 = df_Mobile.iloc[50:60,8:9]#BAM
Target_BPM_3 = df_Mobile.iloc[60:70,8:9]#BPM
Target_BAD_4 = df_Mobile.iloc[90:100,8:9]#BAD
Target_PD_4 = df_Mobile.iloc[100:110,8:9]#PD
Target_PM_2= df_Mobile.iloc[30:40,8:9]#PM

In [139]:
G1_target = pd.concat([Target_BAL_1, Target_BPL_1]).values
G2_target = pd.concat([Target_CM_2,Target_PM_2]).values
G3_target = pd.concat([Target_BAM_3,Target_BPM_3]).values
G4_target = pd.concat([Target_BAD_4,Target_PD_4]).values
G4_target

array([[4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4]], dtype=int64)

In [140]:

# main_feature_train = np.concatenate((fea_train_G1, fea_train_G2,fea_train_G3,fea_train_G4), axis=0)
# main_target_train=np.concatenate((tar_train_G1, tar_train_G2,tar_train_G3,tar_train_G4), axis=0)
main_feature_test = np.concatenate(( feature_G1,feature_G2,feature_G3,feature_G4), axis=0)
main_target_test=np.concatenate((G1_target,G2_target,G3_target,G4_target), axis=0)
main_target_test


array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4]], dtype=int64)

In [141]:
MOBILE_TRAIN_DSLR_TEST = dTree.predict(main_feature_test)
MOBILE_TRAIN_DSLR_TEST

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2], dtype=int64)

In [142]:

print("\nDesicion Tree")

print("\nEvaluation of DTree Model : \n", classification_report(main_target_test, MOBILE_TRAIN_DSLR_TEST))


Desicion Tree

Evaluation of DTree Model : 
               precision    recall  f1-score   support

           1       0.37      0.75      0.49        20
           2       0.33      0.65      0.44        20
           3       0.00      0.00      0.00        20
           4       0.00      0.00      0.00        20

    accuracy                           0.35        80
   macro avg       0.17      0.35      0.23        80
weighted avg       0.17      0.35      0.23        80



c:\users\u5988116\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
