In [32]:
#Train camera 80 test phone 20
#RGB

In [33]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [34]:
df = pd.read_excel('C:/Users/U5988116/Desktop/SeniorProject/Data/Database/Main/coffee_bean_DSLR_20.xlsx')  
df2 = df 
d1= df.iloc[:, 1:3]
d2= df.iloc[:,4:5]

hi_df = pd.concat([d1,d2], axis=1) #high corr feature
hi_df

Red  Green   Gray
0   19.17  13.49  14.62
1   17.23  12.19  13.16
2   17.39  12.53  13.47
3   16.62  11.73  12.69
4   14.97  10.67  11.50
..    ...    ...    ...
75  15.56  11.16  12.06
76  13.78   9.55  10.43
77  14.76  10.34  11.26
78  13.60   9.54  10.38
79  13.48   9.46  10.29

[80 rows x 3 columns]

In [35]:
df=hi_df
BAL_1 = df.iloc[0:10,0:3] #BAL
BPL_1 = df.iloc[10:20,0:3] #BPL
CM_2= df.iloc[20:30,0:3] #CM
BAM_3 = df.iloc[30:40,0:3]#BAM
BPM_3 = df.iloc[40:50,0:3]#BPM
BAD_4 = df.iloc[50:60,0:3]#BAD
PD_4 = df.iloc[60:70,0:3]#PD
PM_2= df.iloc[70:80,0:3]#PM
PM_2


Red  Green   Gray
70  12.75   8.88   9.68
71  11.96   8.34   9.09
72  12.00   8.33   9.08
73  12.33   8.57   9.35
74  12.42   8.57   9.37
75  15.56  11.16  12.06
76  13.78   9.55  10.43
77  14.76  10.34  11.26
78  13.60   9.54  10.38
79  13.48   9.46  10.29

In [36]:
G1= pd.concat([BAL_1, BPL_1])
feature_G1 = G1.values
G2= pd.concat([CM_2,PM_2])
feature_G2 = G2.values
G3=pd.concat([BAM_3,BPM_3])
feature_G3 = G3.values
G4=pd.concat([BAD_4,PD_4])
feature_G4 = G4.values

In [37]:
df = df2
Target_BAL_1 = df.iloc[0:10,11:12]#BAL
Target_BPL_1 = df.iloc[10:20,11:12]#BPL
Target_CM_2= df.iloc[20:30,11:12]#CM
Target_BAM_3 = df.iloc[30:40,11:12]#BAM
Target_BPM_3 = df.iloc[40:50,11:12]#BPM
Target_BAD_4 = df.iloc[50:60,11:12]#BAD
Target_PD_4 = df.iloc[60:70,11:12]#PD
Target_PM_2= df.iloc[70:80,11:12]#PM
Target_PM_2


Group
70      2
71      2
72      2
73      2
74      2
75      2
76      2
77      2
78      2
79      2

In [38]:
G1_target = pd.concat([Target_BAL_1, Target_BPL_1]).values
G2_target = pd.concat([Target_CM_2,Target_PM_2]).values
G3_target = pd.concat([Target_BAM_3,Target_BPM_3]).values
G4_target = pd.concat([Target_BAD_4,Target_PD_4]).values
G1_target

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int64)

In [39]:
# 80% training and 20% test
fea_train_G1, fea_test_G1, tar_train_G1, tar_test_G1 = train_test_split(feature_G1,G1_target, test_size=0.2, random_state=1)
fea_train_G2, fea_test_G2, tar_train_G2, tar_test_G2 = train_test_split(feature_G2,G2_target, test_size=0.2, random_state=1)
fea_train_G3, fea_test_G3, tar_train_G3, tar_test_G3 = train_test_split(feature_G3,G3_target, test_size=0.2, random_state=1)
fea_train_G4, fea_test_G4, tar_train_G4, tar_test_G4 = train_test_split(feature_G4,G4_target, test_size=0.2, random_state=1)

In [40]:
fea_train_G1

array([[17.39, 12.53, 13.47],
       [16.85, 12.52, 13.41],
       [14.97, 10.67, 11.5 ],
       [12.06,  8.17,  8.97],
       [16.79, 12.02, 12.95],
       [17.23, 12.19, 13.16],
       [15.63, 10.47, 11.53],
       [19.17, 13.49, 14.62],
       [13.04,  8.85,  9.71],
       [12.93,  8.68,  9.55],
       [16.14, 11.6 , 12.49],
       [13.97, 10.03, 10.85],
       [17.91, 12.76, 13.78],
       [13.76,  9.28, 10.21],
       [15.35, 10.31, 11.35],
       [14.46, 10.35, 11.14]])

In [41]:
main_feature_train = np.concatenate((fea_train_G1, fea_train_G2,fea_train_G3,fea_train_G4), axis=0)
main_target_train=np.concatenate((tar_train_G1, tar_train_G2,tar_train_G3,tar_train_G4), axis=0)
main_feature_test = np.concatenate(( fea_test_G1,  fea_test_G2, fea_test_G3, fea_test_G4), axis=0)
main_target_test=np.concatenate((tar_test_G1, tar_test_G2,tar_test_G3,tar_test_G4), axis=0)

In [43]:
dTree = DecisionTreeClassifier(max_depth = 30, min_samples_leaf = 4, max_features = 3)
dTree.fit(main_feature_train,main_target_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=30, max_features=3, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [44]:
ModelDT = dTree.predict(main_feature_test)
ModelDT

array([2, 3, 2, 2, 1, 1, 2, 1, 4, 1, 3, 4, 3, 4, 4, 3], dtype=int64)

In [45]:
main_feature_test

array([[16.62, 11.73, 12.69],
       [11.24,  7.58,  8.34],
       [15.57, 11.12, 11.98],
       [13.21,  8.92,  9.81],
       [12.53,  9.36, 10.08],
       [13.78,  9.55, 10.43],
       [13.51,  9.89, 10.69],
       [12.75,  8.88,  9.68],
       [11.57,  9.42,  9.88],
       [12.81, 10.02, 10.65],
       [11.  ,  9.14,  9.54],
       [ 9.93,  7.66,  8.18],
       [11.66,  9.19,  9.77],
       [ 8.71,  7.24,  7.59],
       [ 9.14,  7.16,  7.62],
       [10.45,  8.59,  9.03]])

In [46]:

print("\nDesicion Tree")

print("\nEvaluation of DTree Model : \n", classification_report(main_target_test, ModelDT))


Desicion Tree

Evaluation of DTree Model : 
               precision    recall  f1-score   support

           1       0.00      0.00      0.00         4
           2       0.25      0.25      0.25         4
           3       0.25      0.25      0.25         4
           4       0.50      0.50      0.50         4

    accuracy                           0.25        16
   macro avg       0.25      0.25      0.25        16
weighted avg       0.25      0.25      0.25        16

